jupyterhub/jupyter-server-proxy

- nbserverproxy/handlers.py
In my testing, query string were being dropped, instead of being sent through to the proxy.  This change fixes things for me.
It's probably more complicated than strictly necessary (we could append '?' when the query string is empty), but it should keep the URLs as close as possible to their original form.
> Pass query strings through proxy

- README.md
- nbserverproxy/handlers.py
- setup.py
I don't think there's any explicit reason for us to whitelist
methods.
Fixes #5
> Support a lot more HTTP methods

- nbserverproxy/handlers.py
POST requests can not have None as body, so instead use an empty byte sequence.
I am actually not sure if this is the "right way" (tm) to fix this. Or what else this potentially breaks in terms of HTTP compliance.
Needs this to make https://github.com/betatim/openrefineder work. I think the real problem is that OpenRefine sends empty bodys for POST requests???
> Do not use None as body for POST requests

- nbserverproxy/handlers.py
Using the `__bases__` attribute stops working if you have a class that inherits from a class that uses the `WebSocketMixin`. Instead use the `inspect` module to get the classes in the ["method resolution order"](https://docs.python.org/3/library/inspect.html#inspect.getmro).
I think this should be more robust. Though I am not sure why we do this trickery, seems a bit weird/smells wrong.
> [MRG] Use MRO method to get base classes

- nbserverproxy/handlers.py
Addresses #39 to fix breaking change for websockets in Tornado 5.1
See http://www.tornadoweb.org/en/stable/releases/v5.1.0.html#tornado-websocket
> The WebSocketHandler.select_subprotocol method is now called with an empty list instead of a list containing an empty string if no subprotocols were requested by the client.
> Only choose subprotocol if subprotocol list is non-empty

- nbserverproxy/handlers.py
- in on_message(), check if the received message is of type bytes and if so, send it on with binary flag
- change 'message is bytes' to isinstance(message, bytes)
> Make sure binary messages are proxied correctly (fixes #50)

- nbserverproxy/handlers.py
fixes problems with notebook status api when producing last_activity timestamp.
i.e. in this line https://github.com/jupyter/notebook/blob/4f9a6cbdd81ed26a7979d993766d7223e1c72e5c/notebook/notebookapp.py#L367
when comparing (max(...)) all timestamps it produces a
TypeError: can't compare offset-naive and offset-aware datetimes
> record api_last_activity as timezone aware timestamp

- nbserverproxy/handlers.py
This change allows handler classes that extend `LocalProxyHandler` to specify additional, or alternative, arguments to `tornado.httpclient.HTTPRequest` when proxying. 
For example, this was needed so that we could increase the `request_timeout` in https://github.com/minrk/nbstencilaproxy to handle the execution of long running cells.
> Allow for additional, or alternative, options for proxy request

- nbserverproxy/handlers.py
I think this will fix the problem we are seeing on mybinder.org with newly built repositories that use RStudio (xref https://github.com/jupyterhub/mybinder.org-deploy/issues/865).
> Convert port number to string before building URL

- nbserverproxy/__init__.py
- nbserverproxy/config.py
- Traitlet based configuration for users to directly
specify what processes they want to start & proxy
- entrypoint based configuration for users to be able
to install a package that can specify how processes
should start
> Allow configuring processes to start be much easier

- docs/server-process.rst
- jupyter_server_proxy/__init__.py
- jupyter_server_proxy/api.py
- jupyter_server_proxy/config.py
- jupyter_server_proxy/static/tree.js
- jupyterlab-server-proxy/src/index.ts
- Use namedtuples rather than just dictionaries
to represent config. This way, we have a shared
definition of ServerProcess objects
- Allow turning off launcher entries for objects
> Refactor code to be cleaner

- jupyter_server_proxy/api.py
- jupyterlab-server-proxy/src/index.ts
This also gives us empty icons when they aren't specified
> Pass in icon_url explicitly to the client

- docs/server-process.rst
- jupyter_server_proxy/config.py
- jupyter_server_proxy/utils.py
- tests/test_utils.py
This lets us add more parameters in the future without
breaking backwards compatibility
> Call command / environment with only args they ask for

- docs/server-process.rst
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
Adds a timeout parameter for the readiness check, this is needed for applications that are slow to start. The default is `5s` which matches the current timeout from https://github.com/yuvipanda/simpervisor/blob/b736f117f30ab59db7fbd2ae7637b9fdf6d0295d/simpervisor/process.py#L19
Adds `{base_url}` as a template parameter for configuring servers. This is useful for applications such as many Django apps which need to know their visible path.
> base_url and timeout server config

- docs/server-process.rst
- jupyter_server_proxy/handlers.py
- setup.py
Our 'readyness' condition check is to make sure we can show
something to the user - it doesn't matter if it is a non-200 response.
Primarily, we were getting 404s and other responses that were causing
issues here - 3xxs were resolved by aiohttp.
> Count process as ready if it can respond

- .travis.yml
- docs/server-process.rst
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- tests/resources/httpinfo.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
This started off as a fix for the `X-Forwarded-Context` `X-ProxyContextPath`. Previously they were always `/proxy/{port}`, now they should be `/server-name` if this is a managed server. Since this is related to the code that controls the URL rewriting I thought I'd add in support for absolute URLs.
I've done some testing with:
```
c.ServerProxy.servers = {
'python-http': {
'command': ['python3', '-m', 'http.server', '{port}'],
},
'python-http-abs': {
'command': ['python3', '-m', 'http.server', '{port}'],
'rewrite': '',
},
}
```
`python-http` should produce logs like
```
"GET / HTTP/1.1" 200 -
```
`python-http-abs` should produce logs like
```
"GET /python-http-abs/ HTTP/1.1" 404 -
```
Also `/proxy-abs/port` is the absolute version of `/proxy/port`
Needs more testing! @jacobtomlinson …
> Configure absolute and server URL prefixes

- docs/server-process.rst
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
Port can be specified for servers, e.g. to listen on port 54321 instead of a random port
```python
python-http-port54321': {
'command': ['python3', './tests/resources/httpinfo.py', '{port}'],
'port': 54321,
}
```
Closes https://github.com/jupyterhub/jupyter-server-proxy/issues/87
> Configure port for servers

- docs/server-process.rst
Otherwise users might be tempted to specify a string value. The docs indicate the unit is seconds.
> Default timeout is 5, not 5s.

- docs/arbitrary-ports.rst
Whilst answering https://github.com/jupyterhub/jupyter-server-proxy/issues/116 I realised `/proxy/absolute/<port>` is missing from the docs.
> Add /proxy/absolute/<port> to arbitrary-ports.rst

- jupyter_server_proxy/websocket.py
As of Tornado v6.0.2 some methods were converted to be async/await capable. See commit:
https://github.com/tornadoweb/tornado/commit/e69becbf8c994be5bfa6584ef72df594b27934b5
Closes: https://github.com/jupyterhub/jupyter-server-proxy/issues/39
> WebsocketHandler.get is async

- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/resources/proxyextension.py
- tests/test_proxies.py
Finishes the work needed for #70, dask/dask-labextension#58.
This allows the developer to specify a non-localhost URI to be proxied. It should be a non-breaking change for users to `LocalProxyHandler`. It seems to work well in my testing, but @yuvipanda and @ryanlovett have a much better idea of the range of places where `jupyter-server-proxy` are deployed.
> Allow for other hosts than `localhost` to be proxied.

- jupyter_server_proxy/websocket.py
`jupyter-server-proxy`'s websocket connection (`PingableWSClientConnection`) does not support WS compression.
When using `jupyter-server-proxy` to proxy a websocket connection, the handshake that occurs during the upgrade only takes into account the proxied websocket server's preferences. That server may (and often will) support compression schemes such as `permessage-deflate`.
In this case, the client will use that compression scheme which will trigger an error in `jupyter-server-proxy` / `tornado` code.
This is exactly what happens in #62 .
The fix is fairly simple: `PingableWSClientConnection` should support all compression schemes and let the client and the proxied server decide how they should communicate.
> Support websocket compression

- contrib/code-server-traitlet/README.md
- contrib/code-server-traitlet/jupyter_notebook_config.py
Traitlet derivative of @betatim's vscode-binder.
> Add code-server-traitlet example.

- docs/server-process.rst
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
Most webservers can be configured to serve a page if a directory `/` is accessed, or to redirect to a different path. This PR adds this functionality to jupyter-proxy-server.
For example, when using noVNC the default page is a directory listing. With this PR you can map `/` to `vnc_lite.html`.
E.g. https://gist.github.com/manics/7d1f4b76ce06c2bb07db88e3496a1561
> Optionally map requested → proxied paths

- jupyterlab-server-proxy/README.md
- jupyterlab-server-proxy/package.json
This allows JupyterLab maintainers to make the npm releases.
> Move npm package to jupyterlab org

- contrib/template/{{cookiecutter.project_name}}/jupyter_{{cookiecutter.project_name}}_proxy/__init__.py
In line with the documentation the correct key for the path of the icons folder in the launcher_entry is icon_path and not icon_url. See https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html
This PR is a solution for issue #162
> Replace icon_url with icon_path in __init__.py.

- docs/server-process.rst
The previous link was using the markdown syntax.
> Fix Traitlets link in server process docs

- jupyterlab-server-proxy/package.json
- jupyterlab-server-proxy/tsconfig.json
Fixes #173
At least, I think this fixes #173, I have not verified the functionality but only verified I could build it without failures after bumping it. Also, note the comment in the second commit for an explanation about the change in tsconfig.json
> Support usage of JupyterLab 2.0.0

- jupyter_server_proxy/handlers.py
- jupyter_server_proxy/websocket.py
- tests/resources/jupyter_server_config.py
- tests/resources/websocket.py
- tests/test_proxies.py
> Proxy Websocket subprotocols

- jupyter_server_proxy/handlers.py
- tests/test_proxies.py
Currently if there is special character in the proxied path, it failed with error, e.g:
```bash
[E 16:28:29.202 NotebookApp] Uncaught exception GET /myservice/static/Desktop/Screenshot%202020-03-10%20at%2021.50.46.png (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:9527', method='GET', uri='/myservice/static/Desktop/Screenshot%202020-03-10%20at%2021.50.46.png', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
File "/Users/me/miniconda3/envs/myservice/lib/python3.6/site-packages/tornado/web.py", line 1703, in _execute
result = await result
File "/Users/me/miniconda3/envs/myservice/lib/python3.6/site-packages/jupyter_server_proxy/websocket.py", line 96, in get
return await self.http_get(*args, **kwargs)
File …
```
> Quote proxied_path to make it a safe URL (fixes #138)

- jupyter_server_proxy/handlers.py
This PR aims to fix https://github.com/jupyterhub/jupyter-server-proxy/issues/182, it:
1. Increase the `connect_timeout=250.0, request_timeout=300.0` (both defaults to 20s) (these two values are used as default for FireFox).
2. Capture the timeout error, return `599: Timeout during request` rather than `500: Internal Server Error`.
> Capture request timeout error and increase the timeout value

- jupyter_server_proxy/config.py
ServerProxy command if callable should return a list, while in the docstring it says it should return a dictionary.
> Fix expected type of ServerProxy command callable

- jupyter_server_proxy/static/tree.js
All server process entries shared the same class named after rstudio.
> Set list item class as sever_process.name in tree.js

- jupyterlab-server-proxy/src/index.ts
Currently, when a server proxy launcher is entry is not enabled in the configuration file, the server proxy command is not added to the command registry. Other extensions could be interested in handling the launcher entries while jupyterlab-server-proxy handles the registration of the commands.
This is the case for [jupyterlab-lmod extension](https://github.com/cmd-ntrf/jupyter-lmod), where we want to show the launcher button only when the corresponding software module is loaded. I have made a short video of the workflow https://youtu.be/EQOGcoK2mSE. In order to achieve what is demonstrated, I had to copy the code for the command creation and launcher entry adding from jupyter-server-proxy in jupyter-lmod.
> In JupyterLab, add proxy to command registry even if launcher entry is disabled

- jupyterlab-server-proxy/src/index.ts
The old character 🡕 is a relatively obscure sans-serif variant of the more standard arrow ↗, the later of which should have much better coverage.
This should solve #200.
If we want to do even better, several alternatives are available in [this SO question](https://stackoverflow.com/questions/1899772/new-window-icon-for-web-accessibility).
> Use more common Unicode arrow

- docs/examples.rst
- docs/index.rst
Add an "Examples" section to the documentation, to be able to look-up existing configuration for `jupyter-server-proxy`.
It also references the [`jupyter-server-proxy`](https://github.com/topics/jupyter-server-proxy) topic on GitHub as mentioned in https://discourse.jupyter.org/t/jupyter-server-proxy-gallery/1603
> Add an Examples section to the documentation

- jupyter_server_proxy/handlers.py
My remote proxies weren't working due to the wrong base path being provided in the headers.
I think the diff of the docstring in `_get_context_path` explains the situation perfectly. ;)
> Fix missing host in _get_context_path

- docs/examples.rst
Adds `jupyter-proxy-server` example to the documentation for [Pluto.jl.](https://github.com/fonsp/Pluto.jl).
> Adds Pluto notebook example

- jupyter_server_proxy/handlers.py
I'm not sure exactly what is going on here, but we're seeing an error with this statement on Python 3.9:
```
File "/[snip]/lib/python3.9/site-packages/jupyter_server_proxy/handlers.py", line 489, in ensure_process
with (await self.state['proc_lock']):
TypeError: object Lock can't be used in 'await' expression
```
See https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock
I think this also works in Python 3.5: https://docs.python.org/3/whatsnew/3.5.html#pep-492-coroutines-with-async-and-await-syntax
> Use the recommended async with syntax to acquire and release an asyncio Lock

- docs/examples.rst
Since the project has now been moved to https://github.com/mamba-org/gator.
> Rename the mamba-navigator example to gator in the documentation

- docs/server-process.rst
The current arguments are documented as a list which means it's not possible to link to an anchor within the page.
For example, in https://github.com/jupyterhub/jupyter-rsession-proxy/issues/95#issuecomment-766348946 I wanted to link directly to `absolute_url`, but I could only link to the page.
> Replace server-process list with linkable headings

- .github/workflows/test.yaml
- CONTRIBUTING.md
- README.md
I struggled a while with `pip install -e .` not functioning because I copied CI instructions from test.yaml because I didn't see any setup instructions in the CONTRIBUTING.md that we had. I found later that the README.md had instructions though.
So, I made a note in the README.md and test.yaml to look in CONTRIBUTING.md where I described also described how to run tests.
> docs: mv local dev setup to CONTRIBUTING.md and document tests

- CHANGELOG.md
- setup.py
After upgrading to using ServerApp I stopped being able to use /rstudio.
> When I was using NotebookApp, visiting `/user/erik/rstudio/` would work fine. Now when I'm using ServerApp and JupyterHub 1.3.0, it seems that visiting `/user/erik/rstudio/` redirects to `/auth-sign-in?appUri=%2F` which bounce to `/hub/auth-sign-in?appUri=%2F` which jupyterhub doesn't recognize and responds with 404.
This question in gitter jupyter/jupyter_server led to @blink1073 helping out!
> hi @consideRatio! It looks like jupyter-server-proxy needs a new release with jupyterhub/jupyter-server-proxy#235.
So, here is a PR to release 1.6.0 of the Python package. The JupyterLab extension is already updated since last changed, version 2.1.2.
I generated it with …
> Bump to 1.6.0 (setup.py) and add CHANGELOG.md

- .github/workflows/publish.yaml
https://github.com/jupyterhub/jupyter-server-proxy/pull/245 incorporates the JupyterLab extension into the Python package and uses a single version number for both, which means when it's merged we can publish everything automatically.
This adds a new `Publish` workflow where the build and publish steps for PyPI and NPM are copied from
https://github.com/manics/jupyter-offlinenotebook/blob/340e0e7ac80f01d276c2e68d03144fe1078d5c86/.github/workflows/build.yml#L57-L72
https://github.com/manics/jupyter-offlinenotebook/blob/340e0e7ac80f01d276c2e68d03144fe1078d5c86/.github/workflows/build.yml#L118-L161
This requires two repository secrets:
> Add publish PyPI and NPM workflow

- tests/test_proxies.py
We had a false positive test because it was `return`-ing before its assertions which was the actual test. With this updated test I make the current behavior clear, but I also document in the docstring a FIXME that this is only the current behavior verified with a test, not that it is the desired behavior which isn't known to me.
Closes #239
This is no fix for #109, but it highlights that you can get that kind of error when ?token=wrongtoken is passed to the Jupyter Notebook server, which probably is an issue with notebook server. Right?
> tests: remove bad test, add new clarifying current behavior

- .github/workflows/test.yaml
- jupyter_server_proxy/__init__.py
- jupyter_server_proxy/api.py
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- jupyter_server_proxy/websocket.py
- setup.py
- tests/resources/jupyter_server_config.py
- tests/resources/proxyextension.py
This also includes a commit https://github.com/jupyterhub/jupyter-server-proxy/commit/171c8b89bb50541793883ceb2bb6852af442ab9c which should fix the `TypeError: object NoneType can't be used in 'await' expression` problem mentioned in
https://github.com/jupyterhub/jupyter-server-proxy/blob/885cf001a1d41791240400a64b6765a7aeca9a9f/tests/test_proxies.py#L69-L78
EDIT by Erik: Closes #109 I think
> Switch from notebook to jupyter-server

- .github/workflows/test.yaml
- CHANGELOG.md
- README.md
- docs/contributing/release.rst
- jupyterlab-server-proxy/package.json
> docs: updates to changelog, readme, release for the 3.0.0 release

- setup.py
Closes #258 
```sh
$ ls dist
jupyter-server-proxy-3.0.0.tar.gz           jupyter_server_proxy-3.0.0-py3-none-any.whl
```
The `.tar.gz` file now has the correct name.
> Fix PyPI url

- CHANGELOG.md
- MANIFEST.in
This should fix the conda packaging issues in https://github.com/conda-forge/jupyter-server-proxy-feedstock/pull/20
> Include jupyterlab-server-proxy in the sdist

- CONTRIBUTING.md
This is just a minor documentation tweak.  Starting the server to run tests is much faster if you don't open a browser window as well.
> Open browser not required for running pytests

- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/resources/websocket.py
- tests/test_proxies.py
> Apply `request_headers_override` to websocket requests

- README.md
Hi, was reading about it after a friend pointed `jupyter-server-proxy`. The `CONTRIBUTING.md` link is not rendered on GitHub UI. Not sure if there's some way to auto link the file in Markdown, or if it was supposed to be a link but just missed the final part?
Thanks!
> Fix link to contributing.md

- jupyter_server_proxy/handlers.py
I'm using this package in an environment that happens to have an older version of Tornado. When I attempted to open a Websocket connection through the proxy I experienced this traceback:
```
Traceback (most recent call last):
File "<ENV>/lib/python3.7/site-packages/tornado/web.py", line 1468, in _stack_context_handle_exception
raise_exc_info((type, value, traceback))
File "<string>", line 4, in raise_exc_info
File "<ENV>/lib/python3.7/site-packages/tornado/stack_context.py", line 316, in wrapped
ret = fn(*args, **kwargs)
File "<ENV>/lib/python3.7/site-packages/tornado/websocket.py", line 502, in <lambda>
self.stream.io_loop.add_future(result, lambda f: f.result())
File "<ENV>/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File …
```
> Simplify wait logic for websocket connection

- jupyter_server_proxy/__init__.py
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- jupyter_server_proxy/websocket.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
Hey all, here's what I came up with to resolve #202.
I seem to have achieved my original goal, but there's quite a lot I'm dissatisfied about.
1. In order to be able to read the config in the appropriate spots, I ended up having to change the signatures of several functions. Will this cause breakage in other projects? Is there some better way which I didn't see?
2. I couldn't make my new `rewrite_response` function take just `response` as input without losing important information. Thus I modified my original specification, and `rewrite_response` is now a function of `host`, `port`, `path`, and `response`.
3. I had to implement a near-duplicate function `non_service_rewrite_response` to handle the `/proxy/` endpoint. In this case I'm skeptical of the `jupyter-server-proxy` design. Namely, …
> Add rewrite_response

- jupyter_server_proxy/handlers.py
When simply checking if the server that we're proxying to is up, I think it would make sense to not follow redirects and just interpret redirection as success. In my case this fixed an infinite redirection loop which occurred when proxying to an Rstudio server.
> fix: do not follow redirects when checking if server is up

- jupyter_server_proxy/handlers.py
Thanks for this extremly helpful package. Exposing applications like `code-server` using `jupyter-vscode-proxy` via an inverting proxy e.g. `gcr.io/inverting-proxy` fails due to not allowed cross origin websockets. This seccurity rule was  introduced in `tornado>=4` see [`check_origin`](https://github.com/tornadoweb/tornado/blob/2047e7ae3c825bf52dad10cc8402d09e11091bc1/tornado/websocket.py#L489) and its doc string. `jupyter-server` provides a configurable `check_origin` function consuming `allow_origin` and `allow_origin_pat` being very fine tunable cross origin permissions. This PR exposes the `jupyter-server-proxy` to this functionality and being similar configured as the `jupyter-server` regarding cross origin acceptance. 
Please comment/review I'm open to suggestions and feedback.
> propagate check_origin of JupyterHandler to enable CORS websocket access

- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
Building on #300, illustrating my idea of implementing a `RewritableResponse` class. I tried to use Traitlets to make my data class, since it's used throughout the Jupyter ecosystem, but I don't know it very well.
I was originally thinking of having `RewritableResponse` be the *return* type as well as the input type, but I found this awkward. Now I have `rewrite_response` mutating the `RewritableResponse` object. ~~But this makes the variable names a bit awkward... in order for the variable names to make sense, I now define `original_response` run `rewrite_response(original_response)`, define `rewritten_response` as `original_response` and then delete `original_response`. There must be a better way which I'm not seeing at the moment.~~
> Class-based rewrite response

- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
This builds on @maresb 's work in #209 and enables one to also alter response HTTP headers and status code/reason.  Thanks to @yuvipanda for the idea!
> Enable rewrite_response to modify status and headers

- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
I noticed an annoying discrepancy between Tornado's `HTTPResponse` and my `RewritableResponse` when changing the HTTP code. In Tornado, the `.reason` attribute defaults to the text corresponding to the `.code` attribute. However, in `RewritableResponse`, we expect the `.code` attribute to be changed. If you change `.code`, then `.reason` retains the text generated for the previous code. In this PR, I add an observer which updates the `.reason` attribute if `.code` has changed and `.reason` still has its default value.
I also extended the documentation to illustrate more of the functionality provided, and extended the tests accordingly.
> Set reason according to response code

- CHANGELOG.md
- jupyter_server_proxy/config.py
I just figured we should try cut releases somewhat regularly, and that it could be about time to do so.
I'll consider a merge of this PR as a signal to make a release as well btw.
Note that if we label PRs ahead of time with new/enhancement/bug/maintenance, the cli `github-activity` will automatically help us when we create the CHANGELOG.md file. If you merge a PR.
I've added a documentation typo as part of this PR.
- Fix headings in changelog
- Add changelog for v3.1.0
- Add changelog for v3.2.0
- Fix documentation typo about launcher_entry.path_info (Closes #302)
> Add changelog for 3.1.0 (already released) and 3.2.0 (unreleased)

- .github/workflows/test.yaml
- jupyter_server_proxy/__init__.py
- jupyterlab-server-proxy/package.json
- jupyterlab-server-proxy/yarn.lock
- setup.py
- fixes #306
Not knowing/using `jupyter-packaging` much, I did the following:
```bash
cd jupyterlab-server-proxy
rm yarn.lock
jlpm
jlpm build:prod
```
And seemed to have a working extension. I also bumped the version of `@jupyterlab/builder` to be of the line that generates `third-party-licenses.json`: as it turns out, it only ships the shims for `css-loader` and `style-loader`. As the `style/index.css` is actually empty, we _could_ ship with _no dependencies whatsoever_ without losing any functionality, which is actually quite attractive.
Apropos #298, I restored one old-school compatibility name to make `jupyter serverextension enable` work.
I had some `pip` issues (due to my environment no doubt), but rolled back any changes there except adding the relatively-new Lab trove classifiers. …
> resolve yarn.lock, bump builder version, some packaging metadata

- jupyterlab-server-proxy/src/index.ts
- fixes #308
- removes empty `index.css` and reference to it in `index.ts`
- by extension, removes the need to ship `style-loader` and `css-loader` runtimes
- `third-party-licenses.json` will still be created, but will be empty
> Remove empty JupyterLab style

- .github/workflows/publish.yaml
Specifying branches means tags must also be specified: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
https://github.com/jupyterhub/jupyter-server-proxy/pull/310
> Run publish workflow for tags

- contrib/theia/README.rst
Preformatted `` not allowed inside inline role.
> Yarn link malformed.

- jupyter_server_proxy/handlers.py
In SageMaker Notebook several ML tools do not work, including `aim`, `lit`, `mlflow`, `streamlit`, etc. 
The reason: `jupyter-server-proxy` fails on POST requests if the client sends the body using `Transfer-Encoding: chunked`.
`TensorBoard` does work only because of a workaround solution of replacing all the `POST` requests with `GET`s.
**In more detail:**
The `Transfer-Encoding` is used by http client to specify whether the `POST` method streams without need of knowing content length ahead of time.
Client request path is roughly:
```
[1] Client Browser  -> [2] AWS SageMaker Proxy  -> [3] Jupyter Server Proxy a.k.a. nbserverproxy
|
v
[4] Some Server (Aim / MLFlow / Streamlit / Lit / etc)
```
Now, forwarding some headers, including `Transfer-Encoding` is wrong because the transfer …
> [bugfix] Hop by hop header handling

- .github/workflows/test.yaml
nbclassic 0.3.7 (required by jupyterlab) automatically installs notebook, but the recently released 0.4.2 doesn't. I think this is because nbclassic 0.4+ now includes all the frontend content that was previously in the notebook package. Since jupyter-server provides the backend for nbclassic it doesn't require notebook.
> Install `notebook<7` for notebook test

- docs/server-process.rst
The file has to be named `jupyter_server_config.py` when using JupyterLab and version of Notebook >= 6.5. 
This is because jupyter-server is replacing the notebook backend:
https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html
It might be better to actually explain how the file should be named based on the version used, but I wanted to provide a starting point for the conversation.
> Fix config filename in config via traitlets doc

- .github/workflows/test.yaml
- tests/acceptance/Classic.robot
- tests/acceptance/Lab.robot
- tests/acceptance/__init__.robot
- tests/acceptance/test_acceptance.py
I figure the most important versions to test are the oldest and newest. But,  it can help to know if something is just too old or just too new to function as well.
With this PR I update the CI system to run against py36, 37, 310, and 311, instead of py36, 37, 38, 39.
> ci: test against modern python versions and fix broken test suite

- .github/workflows/test.yaml
- setup.py
For reference jupyterhub/jupyterhub has also dropped support for Python 3.6, and it has reached end of life 10 months ago. Requiring Python 3.7+ for the next release of this software seems very reasonable.
> Drop support for Python 3.6

- RELEASE.md
- pyproject.toml
We have adopted `tbump` to do commit/tag/push in several other jupyterub org repos and I'm very positive about the experience so far even though I was quite skeptical initially.
> Refine RELEASE.md with tbump

- README.md
I thought there was already a warning in this repo, but it doesn't look like it. For comparison:
https://github.com/jupyterhub/jupyter-rsession-proxy#multiuser-considerations has a warning.
Closes https://github.com/jupyterhub/jupyter-server-proxy/issues/358
> README: warn about unlimited local network access

- .github/workflows/test.yaml
As seen [here](https://github.com/actions/runner-images/blame/e9b59a540ed5e360dbdbc018830daa828f9ec067/images/linux/Ubuntu2204-Readme.md?plain=1#L164-L180), firefox and geckodriver as needed by browser simulation tests in our CI system is now available in the ubuntu-22.04 environment. So, due to that we upgrade to use it.
> ci: use ubuntu-22.04, firefox and geckodriver now available

- docs/source/server-process.rst
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- jupyter_server_proxy/unixsock.py
- jupyter_server_proxy/websocket.py
- tests/resources/httpinfo.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
**Updated description**
Unix sockets are an alternative to TCP sockets for local servers: the server listens (and the client connects) on a filesystem path, rather than a numeric port. The big advantage is that, with the right filesystem permissions, the OS can prevent other users (except root) from connecting to a Unix socket, so it's more secure on a multi-user system. See #321 for more details.
This PR adds support for named proxies (those defined in config) to forward to a Unix socket rather than a TCP socket.
- If you set `unix_socket=True` in [server process config](https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html), JSP will create a temporary directory, and fill the new `{unix_socket}` command template argument with a path inside there, where the server can …
> Support proxying to a server process via a Unix socket

- .gitignore
- CONTRIBUTING.md
- jupyter_server_proxy/__init__.py
- pyproject.toml
- Fixes #389
EDIT by Erik: for a background of changes, see https://github.com/jupyterhub/jupyter-server-proxy/issues/389#issuecomment-1500869356
> Fix editable install and update CONTRIBUTING.md

- .github/workflows/test.yaml
- CONTRIBUTING.md
- jupyter_server_proxy/__init__.py
- jupyter_server_proxy/config.py
- pyproject.toml
- tests/conftest.py
- tests/pytest.ini
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
- fixes #309
- fixes #378 
- further isolate the test environment with e.g. custom `$HOME` (tricky on windows)
- split up existing `test_proxies.py` into smaller files
- potentially move some more repetitive things to fixtures
- add parameterization of `--tornado_settings base_url=/foo/bar/` to test nested paths
- fix more test warnings
- hoist new test warnings to errors
- improve speed
- starting a sever takes about 1.5s
- can be challenging to get the `scope` correct with e.g. `tmp_path`
- the widely-used `pytest-xdist` can run tests in parallel for a _moderate_ speedup, but carries some additional costs
- some ports, etc. in the `jupyter_server_config.py`, and tests, still hard-coded, and would collide
> Use `pytest.fixture`s for starting servers, use `importlib*metadata`

- .github/workflows/test.yaml
- CONTRIBUTING.md
- README.md
- docs/source/launchers.md
- pyproject.toml
This PR is based on top of #393 as I'm modifying the docs also modified there. This PR includes only one commit, [369e5b](https://github.com/jupyterhub/jupyter-server-proxy/pull/394/commits/b369e5bb54105372ded580e84afddc2b7a4e831b).
With this PR, the JupyterLab extension will still be published as an NPM package to @jupyterhub/jupyter-server-proxy, but we will not test against it or ensure future functioning, or document how to install it etc. Dropping support for jupyterlab 2 was proposed to go with the 4.0.0 release planned in(#388 as jupyterlab 4 is coming out and we are to support both jupyterlab 3 and 4 already.
> maint, breaking: drop support for jupyterlab 2

- pyproject.toml
Our package is described to support use with windows, but we are not there yet. Pending work to support this, we remove the description that we support it.
- #147 
- #181 
- #392 
- https://github.com/jupyterhub/simpervisor/pull/26
> maint: update package description to not claim windows support

- .github/workflows/publish.yaml
Without this, we error as reported in https://github.com/jupyterhub/jupyter-server-proxy/issues/388#issuecomment-1516475532.
I made the PyPI release manually using the built wheel and source distribution for the 4.0.0 release though.
> ci: cleanup stashed SHA256 checksum before publish to PyPI

- pyproject.toml
This will hopefully fix the CI failures looking like this:
```
tests/acceptance/test_acceptance.py::test_robot ==============================================================================
Acceptance :: Acceptance tests for jupyter-server-proxy                       
==============================================================================
Acceptance.Classic :: Server Proxies in Notebook Classic                      
==============================================================================
Notebook Classic Loads                                                | FAIL |
Parent suite setup failed:
TypeError: __init__() got an unexpected keyword argument 'firefox_profile'
```
https://github.com/robotframework/SeleniumLibrary/issues/1836
> Work around incompatibility (missing firefox_profile arg) for acceptance tests

- jupyter_server_proxy/handlers.py
I started to experiment with serving things via Unix sockets (#337), but when I have two separate proxied services, I could only reach one via Jupyterhub; whichever one I used first would also get the requests meant for the other. This change fixes that.
This seems to be because Tornado's HTTP client objects are singletons by default - [the docs](https://www.tornadoweb.org/en/stable/httpclient.html#tornado.httpclient.AsyncHTTPClient) say:
> instances are reused as a kind of pseudo-singleton (one per [IOLoop](https://www.tornadoweb.org/en/stable/ioloop.html#tornado.ioloop.IOLoop)). The keyword argument `force_instance=True` can be used to suppress this singleton behavior. Unless `force_instance=True` is used, no arguments should be passed to the …
> Ensure proxying to Unix sockets constructs separate HTTP clients

- labextension/yarn.lock
Based on following the instructions in RELEASE.md pending 4.1.0 release, this refreezes the yarn.lock file for us.
Test failures unrelated and tracked in #421
> labextension: refreeze yarn.lock

- docs/source/changelog.md
I think its worth getting a release out for #419 that makes the jupyterlab extension work in jupyterlab 4 environments, and looking at the related bugfix #415, it also seems quite important for users of the unix_socket feature.
> Add changelog for 4.1.0

- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
If a server has a callable as the environment, jupyter-server-proxy formatted it twice. 
If that callable returned an escaped var (i.e. `{ "MYVAR": "{{var}}" }`), the server was crashing when doing the second formatting (as "var" does not exist).
```python
>>> myVar = "{{var}}"
>>> myVar = myVar.format({})
>>> myVar = myVar.format({})
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
KeyError: 'var'
```
With this PR I only format once, wether it's callable or dict.
> Fix double formatting of callables (`command`, `environment`, `request_headers_override`)

- .github/workflows/test.yaml
The code coverage action didn't find a data file of relevance to upload (`coverage.xml`). I've now made sure it finds it.
Things improved, but its messy due to launching `pytest` from the `build` folder.
> Fix failure to upload code coverage reports

- .github/workflows/test.yaml
We had test failures in main branch (#449), and realizing that something has started failing is often something that goes with tracking what dependencies has changed.
If I think there is a test that has started failing for some reason outside a code change in repo, I do the following:
1. Look at workflows run recently to identify when they last worked and when they started failing
2. Compare `pip freeze` output between succeeding tests and failing tests by copy pasting into `ok.txt` and `fail.txt` and doing `git diff --no-index -U0 -- ok.txt fail.txt` (-U0 means 0 lines of context surrounding changes observed)
This is troublesome if there isn't a workflow run recently though, but having regular runs, for example twice a week, would do the trick.
> ci: schedule test runs twice a week

- .github/workflows/test.yaml
- jupyter_server_proxy/websocket.py
- pyproject.toml
We reference tornado and traitlets directly from our source code, so we should surface those dependecies.
We require `jupyter-server>=1.0`, which [depend on `tornado>=5.0` and `traitlets>=4.2.1`](https://github.com/jupyter-server/jupyter_server/blob/1.0.0/setup.py#L39), so I'm adding our dependency on tornado and traitlets explicitly in this project, putting their lower bounds to those versions - and adding a test to verify our test suite works against those versions.
For reference, note that `jupyter-server==1.1.0` released four years ago requires tornado 6.1, so I figure its safe to assume we can bump these notably without issues in the future.
---
This enables me to better reason about https://github.com/jupyterhub/jupyter-server-proxy/pull/448, as its changing something that is passed …
> List tornado and traitlets as dependencies explicitly, and cleanup unreachable code

- .github/workflows/test.yaml
- jupyter_server_proxy/handlers.py
- pyproject.toml
- tests/resources/websocket.py
- tests/test_proxies.py
This PR ensures we don't pass a blank `Sec-Websocket-Protocol` header ([Sending a blank header is incorrect](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#subprotocols)) when we proxy a websocket. This fixes #442, fixes #445, is assumed to fix #332, and closes #448.
This project currently proxies websockets by first accepting an incomming websocket connection were a subprotocol is established, and then opening a websocket connection to a server to proxy to. This is a problem and can lead to bugs that we now warn about. This PR adds tests to document our current problematic handling.
Thank you @duytnguyendtn, @zoghbi-a, and @benz0li for working this - this is building a lot on their investigation and conclusions, which were critical as I didn't …
> Ensure no blank `Sec-Websocket-Protocol` headers and warn if websocket subprotocol edge case occur

- jupyter_server_proxy/handlers.py
- tests/test_proxies.py
When jupyter-server-proxy proxies websockets, its finalizes the websocket handshake between client/proxy before it initiates the proxy/server websocket handshake.
In #458 released with 4.1.1 earlier today the thinking was that it was a better compromise to not forward all subprotocol choices in the proxy/server handshake if we had prematurely picked a single choice in the client/proxy handshake. This turns out to have introduced a regression though, as at least bokeh had been using secondary subprotocol choices to pass other information such as base64 encoded JSON with keys like `session_id`, `session_expiry` and `__bk__zlib_`.
This commit makes sure we keep passing all requested subprotocols, even though we have prematurely picked a specific ahead of time - which is a bug tracked in …
> Keep proxying all requested subprotocols

- .github/workflows/test.yaml
- pyproject.toml
It turns out our oldest dependency test never ran, it was listed under `exclude` rather than `include`.
When run, it failed. It was not possible to get it to install without pinning misc transient dependencies. I think though, that instead of doing that we should just require the latest jupyter-server 1 version (1.24.0), and that leads to requiring tornado 6.1 and traitlets 5.1. Those in turn have been required for a very long time.
I suggest we go for a merge of this without declaring it a breaking change.
- Fixes #466
> Require jupyter_server 1.24+, tornado 6.1+, traitlets 5.1+

- .github/workflows/linkcheck.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- CONTRIBUTING.md
- pyproject.toml
Rebased on top of #467 for now to avoid merge conflicts. Close / re-open after #467 to view changes without those added.
> Test against Python 3.12

- docs/source/server-process.md
- jupyter_server_proxy/api.py
- jupyter_server_proxy/config.py
- labextension/src/index.ts
- labextension/src/tokens.ts
This lets you set which row of the launcher the icon ends up on (Notebook, Console, or Other).  Just pass a configured launcher_entry.category through to launcher.add, defaulting to Notebook. Also adds documentation for existing `path_info` which was missing.
> Allow configuring jupyterlab launcher category

- jupyter_server_proxy/config.py
I'm not totally sure if this is the fix I need, but I think it is... full disclaimer, I did not test/validate this.
I am in a JupyterLab environment where many servers are registered under the jupyter-server-proxy entrypoints and occassionaly one of them might fail. Trouble is that if one fails, they all fail and no servers are able to be registered and launched (or maybe just subsequent entrypoints fail to register?).
I'd like for jupyter-server-proxy to gracefully handle failures when loading entrypoints so as to not let one failed entrypoint prevent others from loading.
Looking forward to any feedback on these changes and if you all think this would do it
> Prevent failed entrypoints from spoiling the bunch

- CONTRIBUTING.md
Fixed command to link your development version of the extension with JupyterLab and Notebook.
> Fixed jlpm to jupyter in bash command

- docs/source/server-process.md
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
Allows proxy to be configured if it reports back to JupyterHub. In some cases the proxy will always detect background activity which means that the pod will never get culled. In this case you must disable recording and use an alternative source of activity(outside of this MR).
Closes #471
> feat: Allow Skipping of Activity Reporting

- jupyter_server_proxy/_version.py
- pyproject.toml
During our release process, the `_version.py` file wasn't updated as it should been so when inspecting `__version__` we actually just got `4.1.1-0.dev` in the released package where we expected `4.2.0`.
> Fix failure to update __version__

- .github/workflows/test.yaml
Fixes #482 and ensures that we error on pipe failures etc.
> ci: fix test failure on windows and error on bash pipe failures etc

- .github/workflows/test.yaml
I tried removing the python 3.11 pin but ran into the error below, and I don't think it is to be worked in notebook v6, so I've removed the fixme comment instead.
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.12.4/x64/bin/jupyter-notebook", line 5, in <module>
from notebook.notebookapp import main
File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/notebook/notebookapp.py", line 76, in <module>
from .base.handlers import Template404, RedirectWithParams
File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/notebook/base/handlers.py", line 35, in <module>
from notebook.utils import is_hidden, url_path_join, url_is_absolute, url_escape, urldecode_unix_socket_path
File …
```
> ci: remove workaround running test in py311 instead of py312

- docs/source/server-process.md
- jupyter_server_proxy/config.py
- jupyter_server_proxy/rawsocket.py
- jupyter_server_proxy/websockify.py
- tests/resources/jupyter_server_config.py
- tests/resources/rawsocket.py
- tests/test_proxies.py
This incorporates the functionality of websockify by allowing websockets to be proxied to simple TCP or unix socket streams. 
While I understand that websockify already provides a working solution to this problem (see discussion on #75), this seems to have a number of benefits, mainly that it eliminates the extra proxy layer and process that websockify imposes, improving latency and performance overall. It does so with a fairly small amount of code, much smaller and ismpler than websockify itself.
To simplify the instantiation of proxy handlers, this also generalizes and combines the `_make_namedproxy_handler` and `_make_supervisedproxy_handler` functions into a single `_make_proxy_handler` that dynamically determines the class to use, improving flexibility and reducing code duplication, …
> Add `raw_socket_proxy` to directly proxy websockets to TCP/unix sockets

- docs/source/changelog.md
- labextension/yarn.lock
I wanted to get a release out in order to have https://github.com/jupyterhub/jupyter-server-proxy/pull/481 released, as this enables package introspection to verify use of a security patched version.
> Add changelog for v4.3.0

- jupyter_server_proxy/rawsocket.py
One line fix for a missing import in `rawsocket.py`
```
File "/usr/local/lib/python3.11/site-packages/jupyter_server_proxy/rawsocket.py", line 50, in proxy
raise web.HTTPError(405, "this raw_socket_proxy backend only supports websocket connections")
^^^
NameError: name 'web' is not defined
```
> fix: missing tornadoimport for rawsocket handler

- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- jupyter_server_proxy/rawsocket.py
- tests/resources/eventstream.py
- tests/resources/jupyter_server_config.py
- tests/resources/rawsocket.py
- tests/test_proxies.py
currently jupyter-server-proxy does not support the text/event-stream api. when we install https://github.com/hiyouga/LLaMA-Factory in the notebook instance, and access by : http://xxx.xxx/proxy/7860/
the normal request works fine, but the stream API never response.
reference code: https://github.com/ideonate/jhsingle-native-proxy/blob/3e26a4ee0e7318970b7cf6abbd7d88455a9ac621/jhsingle_native_proxy/proxyhandlers.py#L217
> feat: support stream api

- docs/source/changelog.md
As per [RELEASE](https://github.com/jupyterhub/jupyter-server-proxy/blob/main/RELEASE.md) instructions I run `github-activity jupyterhub/jupyter-server-proxy --since v4.3.0`. That gave a bit different format than the previous changelogs, I think because labels were not enforced. I manually split PRs into appropriate groups and adjusted the format to follow that of previous entries.
I think the next version should be either 4.3.1 or 4.4.0. Conservatively I assumed it will more likely be 4.4.0 but please do change it if it is not correct or just let me know and I will fix it up.
CC @yuvipanda :)
> Add changelog for v4.4.0 (?)

- jupyter_server_proxy/config.py
This isn't useful in the jupyter-server-extension, but it should be useful in
https://github.com/jupyterhub/jupyter-server-proxy/pull/501#pullrequestreview-2393608506
An added benefit is this makes it easier to add more parameters in future since the declaration of the class and the handling of defaults is now in the same place.
> Make config.ServerProcess into a Configurable

- jupyter_server_proxy/config.py
When a ServerProcess/Entrypoint provides an explicit title for the LauncherEntry, the path to the application is generated incorrectly.
We encountered this with the [RStudio Proxy](https://github.com/jupyterhub/jupyter-rsession-proxy/blob/main/jupyter_rsession_proxy/__init__.py#L210), which sets `"title": "RStudio"` in the entrypoint. When you click on the icon, you will be redirected to `.../RStudio/` instead of `.../rstudio/`, which will result in a 404. The name of the ServerProcess is `rstudio` and the listener registered on `/rstudio/`
> Wrong path_info generation in LauncherEntry

- jupyter_server_proxy/config.py
simpervisor accepts a float as the timeout (see [here](https://github.com/jupyterhub/simpervisor/blob/main/simpervisor/process.py#L322)), while we currently only accept an int in the traitlets.
Used e.g. in the [RStudio Proxy](https://github.com/jupyterhub/jupyter-rsession-proxy/blob/main/jupyter_rsession_proxy/__init__.py#L142).
> Make ServerProcess.timeout a Float

- docs/source/standalone.md
- jupyter_server_proxy/__init__.py
- jupyter_server_proxy/config.py
- jupyter_server_proxy/standalone/app.py
- jupyter_server_proxy/standalone/proxy.py
- tests/test_standalone.py
As I have mentioned in #507 and #501, I do not think there is a good reason to make `ServerProcess` and `LauncherIcon` a `Configurable`. I like the new approach of using traitlets for these two, but `ServerProxy` is already a Configurable, so I think we should be fine when downgrading them to a `HasTraits`.
I also allowed the entries of `ServerProxy.servers` to be an instance of `ServerProcess`, so users can now do `ServerProxy.servers[name] = ServerProxy(command=[...], ...)` instead of using a dictionary.
> Make ServerProcess and LauncherEntry a HasTraits

- docs/source/server-process.md
in `IconHandler`
https://github.com/jupyterhub/jupyter-server-proxy/blob/8c5906a68f90252951342ccd626e0332f8531872/jupyter_server_proxy/api.py#L71
Reading the icon file is under text (not binary) mode, thus only text-based icon types are supported
by the `icon_path` property. 
The long-term solution would be fixing the `IconHandler` class. 
This PR is a short-team solution, ie, adding description for the `icon_path` mentioning that only text-based 
(well most of cases, SVG) are supported.
> Add icon type description for the `icon_path` property under ServerProxy.servers

- docs/source/server-process.md
- It's 'refine' not 'openrefine'
- We now need to pass -H * to refine to get it to accept requests from any host, otherwise it will reject based on the Host header
Note that this still prevents it from working with the conda-forge feedstock:
https://github.com/conda-forge/openrefine-feedstock/issues/7
> Fix openrefine example commands
