- nbserverproxy/handlers.py
This lets port be string or int without issue
> Use string formatting to form client uri

- nbserverproxy/handlers.py
- setup.py
Abstracted out from nbrsessionproxy.
> Add support for starting & supervising a process when proxying

- nbserverproxy/handlers.py
Unfortunately this also bumps up minimum required Python version to 3.5
in the same commit. I'm ok with that, but should've ideally been a separate PR.  
Fixes #6
> Add support for proxying websockets too

- nbserverproxy/handlers.py
> Handle proxying binary websocket content properly

- nbserverproxy/handlers.py
It looks like Tornado's websocket support is a little weird,
in that the client is asynchronous but the server seems synchronous?
That's a little strange, so we had to do a bunch of ioloop stuff
around this.
Also adds support to downstream SuperviceAndProxy handler for
using websockets properly
> Fix asynchronity issues with websockets

- nbserverproxy/handlers.py
Subclasses have been duplicating this.
> Add AddSlashHandler.

- nbserverproxy/handlers.py
Their absence was being masked by their inclusion in subclasses.
> Add urllib parse functions.

- nbserverproxy/handlers.py
store it in api_last_activity so that the notebook server’s activity monitor will recognize proxied activity
> record proxied activity

- nbserverproxy/handlers.py
> Disable WebSocketProxyHandler which we don't define.

- README.md
- setup.py
* clarify URL to reach server
* minimum python version 3.5
See comments in commit messages
Thanks for this great extension!
> minor improvements to README and setup.py

- nbserverproxy/__init__.py
- nbserverproxy/handlers.py
- nbserverproxy/websocket.py
- setup.py
The [simpervisor library](http://github.com/yuvipanda/simpervisor) 
handles process supervision properly, including:
- Restarting processes when they die
- Readyness checks
- Passing signals to child processes appropriately
We also use a lock to prevent concurrent process starts,
rather than boolean variables.
> Use simpervisor for process supervision

- nbserverproxy/__init__.py
- nbserverproxy/etc/nbextension.json
- nbserverproxy/etc/serverextension.json
- nbserverproxy/static/tree.js
- setup.py
- Makes it easy for all plugins to have a menu entry
without having to write their own nbextension
- Install & enable nbextension & serverextension automatically,
so no extra install command is needed.
> Add entries to 'New' menu with nbextension

- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- setup.py
- Remove f-strings
- Depend on newer simpervisor, which is 3.5 compatible
> Fix python3.5 compatibility

- docs/server-process.rst
This PR add `install_requires` parameter on setup.
this PR solves #90
> Added install_requires parameter

- docs/convenience/new.rst
- docs/convenience/packages/theia.rst
- docs/index.rst
- docs/server-process.rst
Rename from 'contrib' - 'convenience' reflects how people use
it better than 'contrib'
> Add docs on 'convenience' packages

- README.rst
- docs/install.rst
PR relates to issue https://github.com/jupyterhub/jupyter-server-proxy/issues/131
adds note to docs and readme on installing from source
cc @ian-r-rose
> install-doc-update

- jupyter_server_proxy/handlers.py
Before this fix, we could go through https://github.com/jupyterhub/jupyter-server-proxy/blob/90401f1290bc3c5b9408392f8f3b93bde5f55919/jupyter_server_proxy/handlers.py#L82-L83 before the future here https://github.com/jupyterhub/jupyter-server-proxy/blob/90401f1290bc3c5b9408392f8f3b93bde5f55919/jupyter_server_proxy/handlers.py#L262-L263 resolves.
> Fix WebSocket race condition

- .travis.yml
- jupyter_server_proxy/handlers.py
- tests/test_proxies.py
Attempt to fix #185 which is a bi-effect of #177.
I consider this ready for review and merge if you agree with the fix - @oeway and @manics what do you think?
> Quote as little as needed for a valid proxied web request

- .gitignore
- README.rst
There was missing information on the JupyterLab extension which this PR fixes.
> Update readme with labextension info

- jupyter_server_proxy/__init__.py
The extra c got my OCD tingling.
> Rename server_proccesses to server_processes

- jupyter_server_proxy/config.py
IMO, this is a big breaking change that should be a
new major version. We should also try fix all the subprojects
that need fixing before we do this.
> Set `new_browser_tab` to False by default

- jupyter_server_proxy/handlers.py
ref: #211 
Should note: I have not tested this (not sure what that would involve) and am assuming this is a standard logger with a `debug` method.
cc @ryanlovett
> Change subproto logging to debug

- jupyter_server_proxy/handlers.py
This enable to have flask/werkzeug apps seamless integration: see issue #216
> pull request for "adding X_FORWARDED_PREFIX for wsgi compatible apps #216"

- setup.py
Fixes #227
Brings in https://github.com/yuvipanda/simpervisor/pull/7
> Bump simpervisor version

- .github/workflows/build.yaml
It's a complete mystery to me why this didn't cause a CI failure until after the merge ....
> Fix build.yaml workflow

- docs/server-process.rst
- jupyter_server_proxy/__init__.py
- jupyter_server_proxy/config.py
- jupyter_server_proxy/handlers.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
Add support for configurable HTTP headers.
> Allow request header overrides

- jupyter_server_proxy/handlers.py
- tests/test_proxies.py
> More precise regexp matching for /proxy/absolute/<host>:<port>

- jupyter_server_proxy/handlers.py
- tests/resources/gzipserver.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
> keep gzip-encoded content compressed

- .github/workflows/test.yaml
- CONTRIBUTING.md
> Test with lab

- tests/test_proxies.py
Fix a minor test error in https://github.com/jupyterhub/jupyter-server-proxy/commit/fd31930bacd12188c448c886e0783529436b99eb
> Fix test_proxies status code

- jupyter_server_proxy/handlers.py
> allow empty PUT body

- README.md
> Add documentation on how-to disable the extension

- jupyterlab-server-proxy/package.json
Contains #320, #324, #327, #328, #330, #331, #334, #335, #336, #340, #341, and #342.
> Bump version to 3.2.2.

- README.md
Fixing imshields link based on https://github.com/badges/shields/issues/8671
> Fix imshields link README.md

- .github/workflows/test.yaml
- pyproject.toml
- tests/conftest.py
- tests/resources/httpinfo.py
- tests/resources/jupyter_server_config.py
- tests/test_proxies.py
Test https://github.com/jupyterhub/simpervisor/pull/26
> Test Windows

- tests/acceptance/Notebook.robot
- Fixes #449
Thank you @bollwyvl for your help!
> Update tests for notebook 7.1

- docs/source/changelog.md
- Add changelog for 3.2.3
- Add changelog for 4.1.1 and 4.1.2
> Add changelog for 4.1.1 and 4.1.2

- docs/source/server-process.md
> Document the correct default value for new_browser_tab.

- docs/source/changelog.md
- labextension/yarn.lock
> 4.2.0 changelog

- labextension/yarn.lock
Following https://github.com/jupyterhub/jupyter-server-proxy/blob/main/RELEASE.md to release a new version as per https://github.com/jupyterhub/jupyter-server-proxy/pull/479#issuecomment-2317367188
> labextension: refreeze yarn.lock
